

# install:
#     - ./.travis/install.sh
#     - pip install ansible
    

sudo: required

matrix:
    include:

        - dist: xenial
          language: generic
          env: TEST_NAME=01_sanity
        
        - os: osx
          language: generic
          env: TEST_NAME=01_sanity

        - dist: xenial
          language: generic
          env: TEST_NAME=02_install_twice

        - dist: xenial
          language: generic
          env: TEST_NAME=03_install_uninstall

        - dist: xenial
          language: generic
          env: TEST_NAME=04_uninstall

        - dist: xenial
          language: generic
          env: TEST_NAME=05_outputs

services:
  - postgresql

install:
  - ./.travis/install.sh

before_script:
  - psql -c 'create database cloudserver;' -U postgres

script:
  - ansible --version
  - cd $TRAVIS_BUILD_DIR/tests/$TEST_NAME && ./start.sh
