
- name: install Chocolatey
  win_chocolatey:
    name: chocolatey
    state: latest

- name: disable enhanced exit codes
  win_chocolatey_feature:
    name: useEnhancedExitCodes
    state: disabled

- name: install nssm dependency
  win_chocolatey:
    name: nssm
