
- name: make sure rsync is installed
  apt:
    name: rsync
    state: present

- name: make sure java8 is installed
  apt:
    name: java-1.8.0-openjdk-devel
    state: present
  when: install_java | default(false)
