---
- name: sanitize role name
  set_fact:
    sanitize_role_name: "{{ role_name | replace('-', '_') | regex_replace('([^A-Za-z0-9_])', '') | trim }}"

- name: expose role output
  set_fact:
    "{{ sanitize_role_name }}":
      server_port: "{{ server_port }}"
      installation_folder: "{{ installation_folder }}"
      configuration_file: "{{ installation_folder }}/conf/application.properties"
      configuration_xml_file: "{{ installation_folder }}/conf/cloudagent.conf.xml"
      cloud_backup_dir: "{{ cloud_backup_dir }}"
      java_bin: "{{ java_bin }}"
      service_name: "{{ service_name }}"
