
- name: assert all vars are set
  assert: { that: "{{ item }} != '' " }
  with_items:
  - installation_folder
  - service_name
  - temp_folder

- name: gather installed services
  service_facts:

- name: stop the service
  service:
    name: "{{ service_name }}"
    state: stopped
    enabled: no
  when: "service_name in services"
  become: yes

# - name: stop the service
#   systemd:
#     state: stopped
#     enabled: no
#     daemon_reload: yes
#     name: "{{ service_name }}"
  
#   register: service_status
#   failed_when: ( 'Could not find the requested' not in service_status.msg )
#   become: yes

- name: remove the service
  file:
    path: "/etc/systemd/system/{{ service_name }}.service"
    state: absent
  become: yes

- name: remove the application folder
  file:
    path: "{{ installation_folder }}"
    state: absent
  become: yes

- name: remove temp folder
  file:
    path: "{{ temp_folder }}"
    state: absent
  when: clear_temp_folder == True
