
- name: assert all vars are set
  assert: { that: "{{ item }} != '' " }
  with_items:
  - installation_root_folder
  - service_name
  - temp_folder

- name: gather installed services
  service_facts:

- name: stop the service
  service:
    name: "{{ service_name }}"
    state: stopped
    enabled: no
  when: "service_name in services"
  become: yes

- name: remove the service
  file:
    path: "/etc/systemd/system/{{ service_name }}.service"
    state: absent
  become: yes

- name: remove temp folder
  file:
    path: "{{ temp_folder }}"
    state: absent
  when: clear_temp_folder | default('no') | bool

- name: remove tracking files
  file: 
    path: "{{ installation_root_folder }}/{{ item }}"
    state: absent
  with_items:
    - "{{ app_name }}-previous"
    - "{{ app_name }}-current"

- name: find app versions
  find:
    path: "{{ installation_root_folder }}"
    pattern: "{{ app_name }}-*"
    file_type: directory
  register: application_versions

- name: remove application versions
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ application_versions.files }}"
