
- name: install apt dependencies
  block:

    - name: make sure rsync is installed
      apt:
        name: rsync
        state: present

    - name: make sure java8 is installed
      apt:
        name: java-1.8.0-openjdk-devel
        state: present
      when: install_java | default(false)

  when: ansible_pkg_mgr == 'apt'

- name: install yum dependencies 
  block:
    
    - name: make sure rsync is installed
      yum:
        name: rsync
        state: present

    - name: make sure java8 is installed
      yum:
        name: java-1.8.0-openjdk-devel
        state: present
      when: install_java | default(false)

  when: ansible_pkg_mgr == 'yum'
