---

- name: install dependencies
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-dependencies.yml"

- name: gather os specific variables
  include_vars: 
    file: "{{ ansible_os_family | os_family_to_os_type }}.yml"

- name: install
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-install.yml"
  when: state|default('present') == 'present'

- name: apply license
  include_tasks: "tasks/apply-license.yml"
  when: state|default('present') == 'present'

- name: uninstall
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-uninstall.yml"
  when: state|default('present') == 'absent'
