
# set postgres path

- name: set postgres path
  set_fact:
    postgres_install_path: "{{ item.value }}"
  with_dict: "{{ extra_application_properties }}"
  when: "item.key == 'postgres.install.path'"

# validation

- name: assert all vars are set
  assert: { that: "{{ item }} != '' " }
  with_items:
  - db_connection_string
  - db_username
  # - db_password
  - temp_folder
  - cloud_backup_dir
  # - postgres_install_path

# set required variables

- name: set facts
  set_fact:
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M') }}"
    db_name: "{{ db_connection_string.split('/')[3] }}"
    db_host: "{{ db_connection_string.split('/')[2].split(':')[0] }}"
    db_port: "{{ db_connection_string.split('/')[2].split(':')[1] }}"
    backups_before_upgrade_dir: "{{ cloud_backup_dir + '_before_upgrade' }}"


# required dependencies

- name: make sure psql is installed on the machine
  win_command: "psql.exe --version"
  args:
    chdir: "{{ postgres_install_path }}/bin"
  register: psql_test
  ignore_errors: yes
   
- name: make sure pg_dump is installed on the machine
  win_command: "pg_dump.exe --version"
  args:
    chdir: "{{ postgres_install_path }}/bin"
  register: pg_dump_test
  ignore_errors: yes

# - name: fail if psql is not found
#   fail:
#     msg: "psql not found in path {{ postgres_install_path }}/bin"
#   when: psql_test.rc != 0
# 
# - name: fail if pg_dump is not found
#   fail:
#     msg: "pg_dump not found in path {{ postgres_install_path }}/bin"
#   when: pg_dump_test.rc != 0    


# set temp folder and backup directory

- name: make sure temp folder exists
  win_file:
    path: "{{ temp_folder }}"
    state: directory

- name: make sure backup directory exists
  win_file:
    path: "{{ backups_before_upgrade_dir }}"
    state: directory


# backup database before upgrade

- name: backup database before upgrade / install
  block:
    - name: check postgresql is recheable
      win_command: c:\windows\system32\cmd.exe /C "set PGPASSWORD={{ db_password }}&& psql.exe -h {{ db_host }} -U {{ db_username }} -p {{ db_port }} -l"
      args:
        chdir: "{{ postgres_install_path }}/bin"
      register: check_dbname

    - name: if db not exist - write sql file to create database
      win_copy:
        content: "create database {{ db_name }}"
        dest: "{{ temp_folder }}\\{{ db_name }}.sql"
      when: "db_name not in check_dbname.stdout"  
    
    - name: "if db not exist - create empty {{ db_name }} database"
      win_command: c:\windows\system32\cmd.exe /C "set PGPASSWORD={{ db_password }}&& psql.exe -h {{ db_host }} -p {{ db_port }} -U {{ db_username }} -f {{ temp_folder }}\\{{ db_name }}.sql"
      args:
        chdir: "{{ postgres_install_path }}/bin"
      when: "db_name not in check_dbname.stdout"

    - name: run cloudserver database backup
      win_command: c:\windows\system32\cmd.exe /C "set PGPASSWORD={{ db_password }}&& pg_dump.exe -h {{ db_host }} -p {{ db_port }} -U {{ db_username }} -w -Fc {{ db_name }} > {{ backups_before_upgrade_dir }}\\{{ timestamp }}-{{ db_name }}.dump"
      args:
        chdir: "{{ postgres_install_path }}/bin"
      when: "db_name in check_dbname.stdout" 
      
  when: psql_test.rc == 0 and pg_dump_test.rc == 0
