
- name: start the service (windows)
  win_service: 
    name: "{{ service_name }}"
    state: started
  register: winsvc_state
  ignore_errors: True    
  become: yes

- name: read logs if service failed (windows)
  win_shell: "Get-Content -tail 100 {{ installation_folder }}\\logs\\server.err.log"
  when: winsvc_state.failed
  register: error_log

- name: print log file
  debug:
    var: error_log
  when: winsvc_state.failed

- name: fail if start failed
  fail: 
    msg: service start failed
  when: winsvc_state.failed

- name: wait for service to start
  win_health_check:
    url: "http://localhost:{{ health_check_port | default(server_port) }}{{ health_check_uri | default('/manage/info') }}"
    expected_status: "{{ health_check_status | default('200') }}"
    max_retries: "{{ health_check_max_retries | default('20') }}"

- name: get installed version from version.properties file
  slurp:
    src: "{{ installation_folder }}/conf/version.properties"
  register: installed_version
  
- name: print installed version
  debug:
    msg: " Installed version: {{ (installed_version['content'] | b64decode).split('=')[1] }}"

- name: fail if app_version is not equal to installed version
  fail:
    msg: "app_version: {{ app_version }} does not macthed to installed version {{ (installed_version['content'] | b64decode).split('=')[1] }}"
  when: app_version != (installed_version['content'] | b64decode).split('=')[1]
  